// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_9_png);    // assets\9.png
LV_IMG_DECLARE(ui_img_13_png);    // assets\13.png
LV_IMG_DECLARE(ui_img_15_png);    // assets\15.png
LV_IMG_DECLARE(ui_img_2_png);    // assets\2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets\3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets\4.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png
LV_IMG_DECLARE(ui_img_33_png);    // assets\33.png
LV_IMG_DECLARE(ui_img_11_png);    // assets\11.png
LV_IMG_DECLARE(ui_img_12_png);    // assets\12.png
LV_IMG_DECLARE(ui_img_10_png);    // assets\10.png
LV_IMG_DECLARE(ui_img_14_png);    // assets\14.png
LV_IMG_DECLARE(ui_img_16_png);    // assets\16.png
LV_IMG_DECLARE(ui_img_17_png);    // assets\17.png
LV_IMG_DECLARE(ui_img_18_png);    // assets\18.png
LV_IMG_DECLARE(ui_img_19_png);    // assets\19.png
LV_IMG_DECLARE(ui_img_20_png);    // assets\20.png
LV_IMG_DECLARE(ui_img_21_png);    // assets\21.png
LV_IMG_DECLARE(ui_img_22_png);    // assets\22.png
LV_IMG_DECLARE(ui_img_23_png);    // assets\23.png
LV_IMG_DECLARE(ui_img_24_png);    // assets\24.png
LV_IMG_DECLARE(ui_img_25_png);    // assets\25.png
LV_IMG_DECLARE(ui_img_26_png);    // assets\26.png
LV_IMG_DECLARE(ui_img_27_png);    // assets\27.png
LV_IMG_DECLARE(ui_img_28_png);    // assets\28.png
LV_IMG_DECLARE(ui_img_29_png);    // assets\29.png
LV_IMG_DECLARE(ui_img_30_png);    // assets\30.png
LV_IMG_DECLARE(ui_img_31_png);    // assets\31.png
LV_IMG_DECLARE(ui_img_32_png);    // assets\32.png
LV_IMG_DECLARE(ui_img_34_png);    // assets\34.png
LV_IMG_DECLARE(ui_img_35_png);    // assets\35.png
LV_IMG_DECLARE(ui_img_36_png);    // assets\36.png
LV_IMG_DECLARE(ui_img_37_png);    // assets\37.png
LV_IMG_DECLARE(ui_img_38_png);    // assets\38.png
LV_IMG_DECLARE(ui_img_39_png);    // assets\39.png
LV_IMG_DECLARE(ui_img_40_png);    // assets\40.png
LV_IMG_DECLARE(ui_img_41_png);    // assets\41.png
LV_IMG_DECLARE(ui_img_42_png);    // assets\42.png
LV_IMG_DECLARE(ui_img_43_png);    // assets\43.png
LV_IMG_DECLARE(ui_img_44_png);    // assets\44.png
LV_IMG_DECLARE(ui_img_45_png);    // assets\45.png
LV_IMG_DECLARE(ui_img_46_png);    // assets\46.png
LV_IMG_DECLARE(ui_img_47_png);    // assets\47.png
LV_IMG_DECLARE(ui_img_7_png);    // assets\7.png
LV_IMG_DECLARE(ui_img_8_png);    // assets\8.png

LV_FONT_DECLARE(ui_font_B108);
LV_FONT_DECLARE(ui_font_B216);
LV_FONT_DECLARE(ui_font_B432);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_R108);
LV_FONT_DECLARE(ui_font_R81);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
